name: Build Go binaries

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Go Setup
          uses: actions/setup-go@v6
          with:
            go-version: 1.24.3

        - name: Brotli Setup
          run: apt-get update && apt-get install -y libbrotli-dev

        - name: Build
          run: sh build.sh
