name: Build Go binaries

on:
    workflow_dispatch:
    release:
        types: [published]

permissions:
    contents: write
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CGO_ENABLED: "1"
            CGO_FLAGS: ""
        strategy:
            matrix:
                goos: [linux, darwin]
                goarch: [arm64, amd64]
        steps:
        - uses: actions/checkout@v4

        - name: Go Setup
          uses: actions/setup-go@v6
          with:
            go-version: 1.24.3

        - name: Brotli Setup
          run: sudo apt-get update && sudo apt-get install -y libbrotli-dev

        - name: Build ncdtree
          run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build ./cmd/ncdtree/
          
        - name: Build nj
          run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build ./cmd/nj/
